[package]
name = "dojo-test-utils"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Dojo testing utils."

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
